export const EDIT_TODO_LIST = "EDIT_TODO_LIST"
export const ADD_TODO_IN_LIST = "ADD_TODO_IN_LIST"
export const DELETE_TODO = "DELETE_TODO"
export const EDIT_LIST = "EDIT_LIST"
export const ADD_LIST = "ADD_LIST"
export const DELETE_DATA = "DELETE_DATA"